version: '3.8'

services:
  morphlyca-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:                             # ← penting: inject ke build
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
        NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL: ${NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL}
        NEXT_PUBLIC_PRIMEAUTH_REALM_ID: ${NEXT_PUBLIC_PRIMEAUTH_REALM_ID}
        NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID: ${NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID}
        NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI: ${NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI}
        NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL: ${NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL}
        NEXT_PUBLIC_MINIO_PUBLIC_BASE: ${NEXT_PUBLIC_MINIO_PUBLIC_BASE}
        NEXT_PUBLIC_MINIO_ALLOWED_PREFIX: ${NEXT_PUBLIC_MINIO_ALLOWED_PREFIX}
    container_name: morphlyca-frontend
    env_file:
      - .env.production
    ports:
      - "3001:3000"
    networks:
      - morphlyca-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  morphlyca-network:
    driver: bridge