version: '3.8'

services:
  morphlyca-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: morphlyca-frontend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3001
      - NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL=https://api.primeauth.meetaza.com/auth
      - NEXT_PUBLIC_PRIMEAUTH_REALM_ID=7e4cb28a-decc-4300-aea8-1b3c091ccbfe
      - NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID=primeauth-admin
      - NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI=http://localhost:3000/auth/callback
      - NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL=https://api.primeauth.meetaza.com/auth/realms/7e4cb28a-decc-4300-aea8-1b3c091ccbfe/protocol/openid-connect/token
      - NEXT_PUBLIC_MINIO_PUBLIC_BASE=http://localhost:9000
      - NEXT_PUBLIC_MINIO_ALLOWED_PREFIX=facefusion-output/
      - S3_ENDPOINT=http://localhost:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=true
      - S3_OUTPUT_BUCKET=facefusion-output
    volumes:
      - C:\Users\Asyam\Documents\morphlyca-fe:/app
      - /app/node_modules
      - /app/.next
    networks:
      - morphlyca-network
    restart: unless-stopped

  # Hanya MinIO untuk development (backend dan database bisa berjalan terpisah)
  minio:
    image: minio/minio:latest
    container_name: morphlyca-minio-dev
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data_dev:/data
    networks:
      - morphlyca-network
    restart: unless-stopped

volumes:
  minio_data_dev:

networks:
  morphlyca-network:
    driver: bridge