# version: "3.8"   # (boleh dihapus; compose modern nggak perlu)

services:
  morphlyca-frontend:
    image: adminmeetaza/morphlyca-fe:latest   # ← TARIK dari Docker Hub
    container_name: morphlyca-frontend
    # (opsional, kalau compose kamu mendukung) selalu tarik versi terbaru saat up
    # pull_policy: always

    # FE Next.js biasanya tidak butuh env runtime; semua NEXT_PUBLIC_* dibake saat build.
    # Kalau kamu memang pakai runtime-env, boleh tetap pakai env_file:
    # env_file:
    #   - .env.runtime

    ports:
      - "3001:3000"
    networks:
      - morphlyca-network
    restart: unless-stopped

    # Perbaiki healthcheck: wget -f itu salah. Pakai curl -fS, atau wget -qO-.
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  morphlyca-network:
    driver: bridge
