version: '3.8'

services:
  morphlyca-frontend-dev-simple:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: morphlyca-frontend-dev-simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3001
      - NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL=https://api.primeauth.meetaza.com/auth
      - NEXT_PUBLIC_PRIMEAUTH_REALM_ID=8930ef74-b6cf-465a-9a74-8f9cc591c3e3
      - NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID=primeauth-admin
      - NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI=http://localhost:3000/auth/callback
      - NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL=https://api.primeauth.meetaza.com/auth/realms/8930ef74-b6cf-465a-9a74-8f9cc591c3e3/protocol/openid-connect/token
      - NEXT_PUBLIC_MINIO_PUBLIC_BASE=http://localhost:9000
      - NEXT_PUBLIC_MINIO_ALLOWED_PREFIX=facefusion-output/
      - S3_ENDPOINT=http://localhost:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=true
      - S3_OUTPUT_BUCKET=facefusion-output
    # No volumes for Windows testing
    networks:
      - morphlyca-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: morphlyca-minio-dev-simple
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data_dev:/data
    networks:
      - morphlyca-network

networks:
  morphlyca-network:
    driver: bridge

volumes:
  minio_data_dev: