# docker-compose.yml

services:
  morphlyca-frontend:
    image: adminmeetaza/morphlyca-fe:latest   # ← tarik image dari Docker Hub
    container_name: morphlyca-frontend

    # (opsional) selalu tarik image terbaru saat up, kalau Compose kamu mendukung:
    # pull_policy: always

    # semua NEXT_PUBLIC_* didefinisikan di file ini
    # entrypoint di image akan menulisnya ke /public/runtime-env.js saat start
    env_file:
      - .env.production

    ports:
      - "3001:3000"
    networks:
      - morphlyca-network
    restart: unless-stopped

    # Healthcheck (perbaikan: pakai curl -fsS)
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  morphlyca-network:
    driver: bridge