version: '3.8'

services:
  morphlyca-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morphlyca-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3001
      - NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL=https://api.primeauth.meetaza.com/auth
      - NEXT_PUBLIC_PRIMEAUTH_REALM_ID=8930ef74-b6cf-465a-9a74-8f9cc591c3e3
      - NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID=primeauth-admin
      - NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI=http://localhost:3000/auth/callback
      - NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL=https://api.primeauth.meetaza.com/auth/realms/8930ef74-b6cf-465a-9a74-8f9cc591c3e3/protocol/openid-connect/token
      - NEXT_PUBLIC_MINIO_PUBLIC_BASE=http://localhost:9000
      - NEXT_PUBLIC_MINIO_ALLOWED_PREFIX=facefusion-output/
      - S3_ENDPOINT=http://localhost:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=true
      - S3_OUTPUT_BUCKET=facefusion-output
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - morphlyca-network
    restart: unless-stopped
    depends_on:
      - morphlyca-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend service (optional - jika ingin menjalankan bersamaan)
  morphlyca-backend:
    image: morphlyca-backend:latest  # Ganti dengan image backend yang sesuai
    container_name: morphlyca-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@postgres:5432/morphlyca
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - morphlyca-network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio

  # Database
  postgres:
    image: postgres:15-alpine
    container_name: morphlyca-postgres
    environment:
      - POSTGRES_DB=morphlyca
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - morphlyca-network
    restart: unless-stopped

  # Redis for caching/sessions
  redis:
    image: redis:7-alpine
    container_name: morphlyca-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - morphlyca-network
    restart: unless-stopped

  # MinIO for file storage
  minio:
    image: minio/minio:latest
    container_name: morphlyca-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - morphlyca-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  morphlyca-network:
    driver: bridge