#!/usr/bin/env sh
set -e

# Tulis file public/runtime-env.js dari ENV container
cat > /app/public/runtime-env.js <<'EOF'
window.__ENV = {
  NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-}",
  NEXT_PUBLIC_FRONTEND_URL: "${NEXT_PUBLIC_FRONTEND_URL:-}",
  NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL: "${NEXT_PUBLIC_PRIMEAUTH_AUTH_SERVICE_URL:-}",
  NEXT_PUBLIC_PRIMEAUTH_REALM_ID: "${NEXT_PUBLIC_PRIMEAUTH_REALM_ID:-}",
  NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID: "${NEXT_PUBLIC_PRIMEAUTH_CLIENT_ID:-}",
  NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI: "${NEXT_PUBLIC_PRIMEAUTH_REDIRECT_URI:-}",
  NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL: "${NEXT_PUBLIC_PRIMEAUTH_TOKEN_URL:-}",
  NEXT_PUBLIC_MINIO_PUBLIC_BASE: "${NEXT_PUBLIC_MINIO_PUBLIC_BASE:-}",
  NEXT_PUBLIC_MINIO_ALLOWED_PREFIX: "${NEXT_PUBLIC_MINIO_ALLOWED_PREFIX:-}"
};
EOF

exec "$@"